-- MySQL Script generated by MySQL Workbench
-- Tue Oct 11 21:47:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_organorepublic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_organorepublic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_organorepublic` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_organorepublic` ;

-- -----------------------------------------------------
-- Table `db_organorepublic`.`barcodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`barcodes` (
  `ISBN` INT NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`ISBN`),
  CONSTRAINT `FK__barcodes__ISBN__77DFC722`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`barcodesPrinted`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`barcodesPrinted` (
  `ISBN` INT NOT NULL,
  `employeeID` SMALLINT NOT NULL,
  `date` DATE NOT NULL,
  `count` SMALLINT NULL,
  PRIMARY KEY (`ISBN`, `employeeID`, `date`),
  UNIQUE INDEX `ISBN_UNIQUE` (`ISBN` ASC) VISIBLE,
  UNIQUE INDEX `employeeID_UNIQUE` (`employeeID` ASC) VISIBLE,
  UNIQUE INDEX `date_UNIQUE` (`date` ASC) VISIBLE,
  CONSTRAINT `sets_printedBarcodes`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `employee_printedBarcodes`
    FOREIGN KEY (`employeeID`)
    REFERENCES `db_organorepublic`.`employee` (`employeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`barcodesdelivered`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`barcodesdelivered` (
  `orderDate` DATE NOT NULL,
  `ISBN` INT NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`orderDate`, `ISBN`),
  INDEX `FK__barcodesDe__ISBN__78D3EB5B` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `FK__barcodesDe__ISBN__78D3EB5B`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`barcodesorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`barcodesorder` (
  `orderDate` DATE NOT NULL,
  `ISBN` INT NOT NULL,
  `count` INT NOT NULL,
  `price` DECIMAL(19,4) NOT NULL,
  `estShipDate` DATE NOT NULL,
  `estDeliveryDate` DATE NOT NULL,
  PRIMARY KEY (`orderDate`, `ISBN`),
  INDEX `FK__barcodesOr__ISBN__79C80F94` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `FK__barcodesOr__ISBN__79C80F94`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`booklets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`booklets` (
  `bookletID` SMALLINT NOT NULL,
  `bookletType` TINYINT UNSIGNED NOT NULL,
  `count` SMALLINT NOT NULL,
  PRIMARY KEY (`bookletID`, `bookletType`),
  INDEX `FK__booklets__bookle__7ABC33CD` (`bookletType` ASC) VISIBLE,
  CONSTRAINT `FK__booklets__bookle__7ABC33CD`
    FOREIGN KEY (`bookletType`)
    REFERENCES `db_organorepublic`.`booklettype` (`bookletTypeID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`bookletsdelivered`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`bookletsdelivered` (
  `orderDate` DATE NOT NULL,
  `bookletType` TINYINT UNSIGNED NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`orderDate`, `bookletType`),
  INDEX `FK__bookletsD__bookl__7BB05806` (`bookletType` ASC) VISIBLE,
  CONSTRAINT `FK__bookletsD__bookl__7BB05806`
    FOREIGN KEY (`bookletType`)
    REFERENCES `db_organorepublic`.`booklettype` (`bookletTypeID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`bookletsorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`bookletsorder` (
  `orderDate` DATE NOT NULL,
  `bookletType` TINYINT UNSIGNED NOT NULL,
  `count` INT NOT NULL,
  `price` DECIMAL(19,4) NOT NULL,
  `estShipDate` DATE NOT NULL,
  `estDeliveryDate` DATE NOT NULL,
  PRIMARY KEY (`orderDate`, `bookletType`),
  INDEX `FK__bookletsO__bookl__7CA47C3F` (`bookletType` ASC) VISIBLE,
  CONSTRAINT `FK__bookletsO__bookl__7CA47C3F`
    FOREIGN KEY (`bookletType`)
    REFERENCES `db_organorepublic`.`booklettype` (`bookletTypeID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`booklettype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`booklettype` (
  `bookletTypeID` TINYINT UNSIGNED NOT NULL,
  `bookletType` CHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`bookletTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`boxtype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`boxtype` (
  `boxTypeID` TINYINT UNSIGNED NOT NULL,
  `countSets` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`boxTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`brand` (
  `brandID` TINYINT UNSIGNED NOT NULL,
  `brandName` CHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`brandID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`brandsets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`brandsets` (
  `brandID` TINYINT UNSIGNED NOT NULL,
  `ISBN` INT NOT NULL,
  PRIMARY KEY (`brandID`, `ISBN`),
  INDEX `FK__brandSets__ISBN__7E8CC4B1` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `FK__brandSets__brand__7D98A078`
    FOREIGN KEY (`brandID`)
    REFERENCES `db_organorepublic`.`brand` (`brandID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__brandSets__ISBN__7E8CC4B1`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`containers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`containers` (
  `containerID` TINYINT UNSIGNED NOT NULL,
  `containerName` CHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `containerWeight` DOUBLE NOT NULL,
  PRIMARY KEY (`containerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`employee` (
  `employeeID` SMALLINT NOT NULL,
  `emplName` CHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `emplSurname` CHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ratePerHour` DECIMAL(19,4) NOT NULL,
  PRIMARY KEY (`employeeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`inventorization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`inventorization` (
  `seedsID` SMALLINT NOT NULL,
  `date` DATE NOT NULL,
  `emplID` SMALLINT NOT NULL,
  `gros` DOUBLE NOT NULL,
  `tookFromWH` DOUBLE NOT NULL,
  `returnToWH` DOUBLE NOT NULL,
  `invTime` TIME NOT NULL,
  PRIMARY KEY (`seedsID`, `date`, `emplID`, `invTime`),
  INDEX `FK__inventori__emplI__0169315C` (`emplID` ASC) VISIBLE,
  CONSTRAINT `FK__inventori__emplI__0169315C`
    FOREIGN KEY (`emplID`)
    REFERENCES `db_organorepublic`.`employee` (`employeeID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__inventori__seeds__7F80E8EA`
    FOREIGN KEY (`seedsID`)
    REFERENCES `db_organorepublic`.`seeds` (`seedsID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`labelsPrinted`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`labelsPrinted` (
  `ISBN` INT NOT NULL,
  `labelType` TINYINT UNSIGNED NOT NULL,
  `employeeID` SMALLINT NOT NULL,
  `dateP` DATE NOT NULL,
  `rolls` TINYINT NULL,
  `count` SMALLINT NULL,
  PRIMARY KEY (`ISBN`, `labelType`, `employeeID`, `dateP`),
  UNIQUE INDEX `ISBN_UNIQUE` (`ISBN` ASC) VISIBLE,
  UNIQUE INDEX `labelType_UNIQUE` (`labelType` ASC) VISIBLE,
  UNIQUE INDEX `employeeID_UNIQUE` (`employeeID` ASC) VISIBLE,
  UNIQUE INDEX `dateP_UNIQUE` (`dateP` ASC) VISIBLE,
  CONSTRAINT `sets_labelsPrinted`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `type_labelsPrinted`
    FOREIGN KEY (`labelType`)
    REFERENCES `db_organorepublic`.`labeltype` (`labelTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employee_labelsPrinted`
    FOREIGN KEY (`employeeID`)
    REFERENCES `db_organorepublic`.`employee` (`employeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`labelsdelivered`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`labelsdelivered` (
  `orderDate` DATE NOT NULL,
  `ISBN` INT NOT NULL,
  `rolls` TINYINT UNSIGNED NOT NULL,
  `count` SMALLINT NOT NULL,
  `labelType` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`orderDate`, `ISBN`, `labelType`),
  INDEX `FK__labelsDeli__ISBN__07220AB2` (`ISBN` ASC) VISIBLE,
  INDEX `FK__labelsDel__label__08162EEB` (`labelType` ASC) VISIBLE,
  CONSTRAINT `FK__labelsDel__label__08162EEB`
    FOREIGN KEY (`labelType`)
    REFERENCES `db_organorepublic`.`labeltype` (`labelTypeID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__labelsDeli__ISBN__07220AB2`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`labelsorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`labelsorder` (
  `orderDate` DATE NOT NULL,
  `ISBN` INT NOT NULL,
  `rolls` TINYINT UNSIGNED NOT NULL,
  `count` SMALLINT NOT NULL,
  `estShipDate` DATE NOT NULL,
  `estDeliveryDate` DATE NOT NULL,
  `labelType` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`orderDate`, `ISBN`, `labelType`),
  INDEX `FK__labelsOrde__ISBN__04459E07` (`ISBN` ASC) VISIBLE,
  INDEX `FK__labelsOrd__label__090A5324` (`labelType` ASC) VISIBLE,
  CONSTRAINT `FK__labelsOrd__label__090A5324`
    FOREIGN KEY (`labelType`)
    REFERENCES `db_organorepublic`.`labeltype` (`labelTypeID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__labelsOrde__ISBN__04459E07`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`labeltype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`labeltype` (
  `labelTypeID` TINYINT UNSIGNED NOT NULL,
  `ltypeName` CHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`labelTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`lables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`lables` (
  `ISBN` INT NOT NULL,
  `typeOfLabel` TINYINT UNSIGNED NOT NULL,
  `rolls` TINYINT UNSIGNED NOT NULL,
  `count` SMALLINT NOT NULL,
  PRIMARY KEY (`ISBN`, `typeOfLabel`),
  INDEX `FK__lables__typeOfLa__09FE775D` (`typeOfLabel` ASC) VISIBLE,
  CONSTRAINT `FK__lables__ISBN__0AF29B96`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__lables__typeOfLa__09FE775D`
    FOREIGN KEY (`typeOfLabel`)
    REFERENCES `db_organorepublic`.`labeltype` (`labelTypeID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`masterbagblankdelivered`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`masterbagblankdelivered` (
  `orderDate` DATE NOT NULL,
  `typeMBID` TINYINT UNSIGNED NOT NULL,
  `count` SMALLINT NOT NULL,
  PRIMARY KEY (`orderDate`, `typeMBID`),
  INDEX `FK__masterBag__typeM__0BE6BFCF` (`typeMBID` ASC) VISIBLE,
  CONSTRAINT `FK__masterBag__typeM__0BE6BFCF`
    FOREIGN KEY (`typeMBID`)
    REFERENCES `db_organorepublic`.`typeofmasterbag` (`typeMBID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`masterbagblankorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`masterbagblankorder` (
  `orderDate` DATE NOT NULL,
  `typeMBID` TINYINT UNSIGNED NOT NULL,
  `count` SMALLINT NOT NULL,
  `price` DECIMAL(19,4) NOT NULL,
  `estShipDate` DATE NOT NULL,
  `estDeliveryDate` DATE NOT NULL,
  PRIMARY KEY (`orderDate`, `typeMBID`),
  INDEX `FK__masterBag__typeM__0CDAE408` (`typeMBID` ASC) VISIBLE,
  CONSTRAINT `FK__masterBag__typeM__0CDAE408`
    FOREIGN KEY (`typeMBID`)
    REFERENCES `db_organorepublic`.`typeofmasterbag` (`typeMBID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`masterbags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`masterbags` (
  `typeMBID` TINYINT UNSIGNED NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`typeMBID`),
  CONSTRAINT `FK__masterbag__typeM__0DCF0841`
    FOREIGN KEY (`typeMBID`)
    REFERENCES `db_organorepublic`.`typeofmasterbag` (`typeMBID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`masterbagsprinted`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`masterbagsprinted` (
  `dateP` DATE NOT NULL,
  `ISBN` INT NOT NULL,
  `emplID` SMALLINT NOT NULL,
  `count` SMALLINT NOT NULL,
  `reject` SMALLINT NOT NULL,
  `priceForPrinting` DECIMAL(19,4) NOT NULL,
  `typeMBID` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`dateP`, `ISBN`, `emplID`),
  INDEX `FK__masterBag__typeM__0EC32C7A` (`typeMBID` ASC) VISIBLE,
  INDEX `FK__masterBag__emplI__0FB750B3` (`emplID` ASC) VISIBLE,
  INDEX `FK__masterBags__ISBN__10AB74EC` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `FK__masterBag__emplI__0FB750B3`
    FOREIGN KEY (`emplID`)
    REFERENCES `db_organorepublic`.`employee` (`employeeID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__masterBag__typeM__0EC32C7A`
    FOREIGN KEY (`typeMBID`)
    REFERENCES `db_organorepublic`.`typeofmasterbag` (`typeMBID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__masterBags__ISBN__10AB74EC`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`packedseeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`packedseeds` (
  `emplID` SMALLINT NOT NULL,
  `seedsID` SMALLINT NOT NULL,
  `date` DATE NOT NULL,
  `count` SMALLINT NOT NULL,
  PRIMARY KEY (`emplID`, `seedsID`, `date`),
  INDEX `FK__packedSee__seeds__1293BD5E` (`seedsID` ASC) VISIBLE,
  CONSTRAINT `FK__packedSee__emplI__119F9925`
    FOREIGN KEY (`emplID`)
    REFERENCES `db_organorepublic`.`employee` (`employeeID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__packedSee__seeds__1293BD5E`
    FOREIGN KEY (`seedsID`)
    REFERENCES `db_organorepublic`.`seeds` (`seedsID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`packedsets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`packedsets` (
  `emplID` SMALLINT NOT NULL,
  `ISBN` INT NOT NULL,
  `date` DATE NOT NULL,
  `count` SMALLINT NOT NULL,
  PRIMARY KEY (`emplID`, `ISBN`, `date`),
  INDEX `FK__packedSets__ISBN__147C05D0` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `FK__packedSet__emplI__1387E197`
    FOREIGN KEY (`emplID`)
    REFERENCES `db_organorepublic`.`employee` (`employeeID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__packedSets__ISBN__147C05D0`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`reservedbarcodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`reservedbarcodes` (
  `ISBN` INT NOT NULL,
  `date` DATE NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`ISBN`, `date`),
  CONSTRAINT `FK__reservedBa__ISBN__15702A09`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`reservedbooklets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`reservedbooklets` (
  `bookletType` TINYINT UNSIGNED NOT NULL,
  `bookletID` SMALLINT NOT NULL,
  `ISBN` INT NOT NULL,
  `date` DATE NOT NULL,
  `count` SMALLINT NOT NULL,
  PRIMARY KEY (`bookletType`, `bookletID`, `ISBN`, `date`),
  INDEX `FK__reservedBo__ISBN__16644E42` (`ISBN` ASC) VISIBLE,
  INDEX `FK_reservedBooklets_booklets` (`bookletID` ASC, `bookletType` ASC) VISIBLE,
  CONSTRAINT `FK__reservedBo__ISBN__16644E42`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_reservedBooklets_booklets`
    FOREIGN KEY (`bookletID` , `bookletType`)
    REFERENCES `db_organorepublic`.`booklets` (`bookletID` , `bookletType`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`reservedforproduction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`reservedforproduction` (
  `ISBN` INT NOT NULL,
  `seedsID` SMALLINT NOT NULL,
  `date` DATE NOT NULL,
  `weight` DOUBLE NOT NULL,
  PRIMARY KEY (`ISBN`, `seedsID`, `date`),
  INDEX `FK__reservedF__seeds__1D114BD1` (`seedsID` ASC) VISIBLE,
  CONSTRAINT `FK__reservedF__seeds__1D114BD1`
    FOREIGN KEY (`seedsID`)
    REFERENCES `db_organorepublic`.`seeds` (`seedsID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__reservedFo__ISBN__1C1D2798`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`reservedlables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`reservedlables` (
  `dateR` DATE NOT NULL,
  `ISBN` INT NOT NULL,
  `count` SMALLINT NOT NULL,
  `typeOfLabel` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`dateR`, `ISBN`, `typeOfLabel`),
  INDEX `FK__reservedLa__ISBN__1E05700A` (`ISBN` ASC) VISIBLE,
  INDEX `FK__reservedL__typeO__1EF99443` (`typeOfLabel` ASC) VISIBLE,
  CONSTRAINT `FK__reservedL__typeO__1EF99443`
    FOREIGN KEY (`typeOfLabel`)
    REFERENCES `db_organorepublic`.`labeltype` (`labelTypeID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__reservedLa__ISBN__1E05700A`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`reservedmasterbags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`reservedmasterbags` (
  `dateR` DATE NOT NULL,
  `ISBN` INT NOT NULL,
  `typeMBID` TINYINT UNSIGNED NOT NULL,
  `count` SMALLINT NOT NULL,
  PRIMARY KEY (`dateR`, `ISBN`, `typeMBID`),
  INDEX `FK__reservedMa__ISBN__1FEDB87C` (`ISBN` ASC) VISIBLE,
  INDEX `FK__reservedM__typeM__20E1DCB5` (`typeMBID` ASC) VISIBLE,
  CONSTRAINT `FK__reservedM__typeM__20E1DCB5`
    FOREIGN KEY (`typeMBID`)
    REFERENCES `db_organorepublic`.`typeofmasterbag` (`typeMBID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__reservedMa__ISBN__1FEDB87C`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`reservedstickers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`reservedstickers` (
  `dateR` DATE NOT NULL,
  `seedsID` SMALLINT NOT NULL,
  `ISBN` INT NOT NULL,
  `count` CHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`dateR`, `seedsID`, `ISBN`),
  INDEX `FK__reservedSt__ISBN__21D600EE` (`ISBN` ASC) VISIBLE,
  INDEX `FK__reservedS__seeds__22CA2527` (`seedsID` ASC) VISIBLE,
  CONSTRAINT `FK__reservedS__seeds__22CA2527`
    FOREIGN KEY (`seedsID`)
    REFERENCES `db_organorepublic`.`seeds` (`seedsID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__reservedSt__ISBN__21D600EE`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`reservedziplocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`reservedziplocks` (
  `dateR` DATE NOT NULL,
  `ISBN` INT NOT NULL,
  `count` SMALLINT NOT NULL,
  PRIMARY KEY (`dateR`, `ISBN`),
  INDEX `FK__reservedZi__ISBN__23BE4960` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `FK__reservedZi__ISBN__23BE4960`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`salesplan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`salesplan` (
  `ISBN` INT NOT NULL,
  `salesPerMonth` SMALLINT NOT NULL,
  PRIMARY KEY (`ISBN`),
  CONSTRAINT `FK__salesPlan__ISBN__24B26D99`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`seeddeliveredorders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`seeddeliveredorders` (
  `supID` SMALLINT NOT NULL,
  `invoiceNumber` INT NOT NULL,
  `seedsID` SMALLINT NOT NULL,
  `itemWeight` DOUBLE NOT NULL,
  `count` TINYINT UNSIGNED NOT NULL,
  `deliveryDate` DATE NOT NULL,
  PRIMARY KEY (`supID`, `invoiceNumber`, `seedsID`),
  CONSTRAINT `FK_seedDeliveredOrders_seedOrders`
    FOREIGN KEY (`supID` , `invoiceNumber` , `seedsID`)
    REFERENCES `db_organorepublic`.`seedorders` (`supID` , `invoiceNumber` , `seedsID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`seedorders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`seedorders` (
  `supID` SMALLINT NOT NULL,
  `invoiceNumber` INT NOT NULL,
  `seedsID` SMALLINT NOT NULL,
  `itemWeight` DOUBLE NOT NULL,
  `count` TINYINT UNSIGNED NOT NULL,
  `pricePerLb` DECIMAL(19,4) NOT NULL,
  `orderDate` DATE NOT NULL,
  `linkToInvoice` VARCHAR(0) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`supID`, `invoiceNumber`, `seedsID`),
  INDEX `FK__seedOrder__seeds__2A6B46EF` (`seedsID` ASC) VISIBLE,
  CONSTRAINT `FK__seedOrder__seeds__2A6B46EF`
    FOREIGN KEY (`seedsID`)
    REFERENCES `db_organorepublic`.`seeds` (`seedsID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__seedOrder__supID__297722B6`
    FOREIGN KEY (`supID`)
    REFERENCES `db_organorepublic`.`suppliers` (`supID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`seeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`seeds` (
  `seedsID` SMALLINT NOT NULL,
  `seedsName` CHAR(60) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `seedsCategory` TINYINT UNSIGNED NOT NULL,
  `containerID` TINYINT UNSIGNED NOT NULL,
  `countPerLb` INT NOT NULL,
  `seedsType` TINYINT UNSIGNED NOT NULL,
  `seedTypeMachine` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`seedsID`),
  INDEX `FK__seeds__seedsCate__75035A77` (`seedsCategory` ASC) VISIBLE,
  INDEX `FK__seeds__container__75F77EB0` (`containerID` ASC) VISIBLE,
  INDEX `FK__seeds__seedsType__76EBA2E9` (`seedsType` ASC) VISIBLE,
  CONSTRAINT `FK__seeds__container__75F77EB0`
    FOREIGN KEY (`containerID`)
    REFERENCES `db_organorepublic`.`containers` (`containerID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__seeds__seedsCate__75035A77`
    FOREIGN KEY (`seedsCategory`)
    REFERENCES `db_organorepublic`.`seedscategory` (`seedsCategoryID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__seeds__seedsType__76EBA2E9`
    FOREIGN KEY (`seedsType`)
    REFERENCES `db_organorepublic`.`typeofseeds` (`typeSeedsID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`seedscategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`seedscategory` (
  `seedsCategoryID` TINYINT UNSIGNED NOT NULL,
  `categoryName` CHAR(60) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`seedsCategoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`seedschangingtime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`seedschangingtime` (
  `date` DATE NOT NULL,
  `emplID` SMALLINT NOT NULL,
  `session` TINYINT UNSIGNED NOT NULL,
  `timeIN` TIME NOT NULL,
  `timeOut` TIME NOT NULL,
  `machineN` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`date`, `emplID`, `session`),
  INDEX `FK__seedsChan__emplI__2C538F61` (`emplID` ASC) VISIBLE,
  CONSTRAINT `FK__seedsChan__emplI__2C538F61`
    FOREIGN KEY (`emplID`)
    REFERENCES `db_organorepublic`.`employee` (`employeeID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`seedsets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`seedsets` (
  `ISBN` INT NOT NULL,
  `seedsID` SMALLINT NOT NULL,
  PRIMARY KEY (`ISBN`, `seedsID`),
  INDEX `FK__seedSets__seedsI__2E3BD7D3` (`seedsID` ASC) VISIBLE,
  CONSTRAINT `FK__seedSets__ISBN__2D47B39A`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__seedSets__seedsI__2E3BD7D3`
    FOREIGN KEY (`seedsID`)
    REFERENCES `db_organorepublic`.`seeds` (`seedsID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`sets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`sets` (
  `ISBN` INT NOT NULL,
  `setName` CHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `setWeight` DOUBLE NOT NULL,
  `seedsVCount` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ISBN`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`shipments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`shipments` (
  `ISBN` INT NOT NULL,
  `shipmentN` INT NOT NULL,
  `date` DATE NOT NULL,
  `countSets` SMALLINT NOT NULL,
  `storageTypeID` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ISBN`, `shipmentN`, `date`, `storageTypeID`),
  INDEX `FK__shipments__stora__30242045` (`storageTypeID` ASC) VISIBLE,
  CONSTRAINT `FK__shipments__ISBN__2F2FFC0C`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__shipments__stora__30242045`
    FOREIGN KEY (`storageTypeID`)
    REFERENCES `db_organorepublic`.`storagetype` (`storageTypeID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`standartseeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`standartseeds` (
  `seedsID` SMALLINT NOT NULL,
  `seedBrand` TINYINT UNSIGNED NOT NULL,
  `count` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`seedsID`, `seedBrand`),
  INDEX `FK__standartS__seedB__320C68B7` (`seedBrand` ASC) VISIBLE,
  CONSTRAINT `FK__standartS__seedB__320C68B7`
    FOREIGN KEY (`seedBrand`)
    REFERENCES `db_organorepublic`.`brand` (`brandID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__standartS__seeds__3118447E`
    FOREIGN KEY (`seedsID`)
    REFERENCES `db_organorepublic`.`seeds` (`seedsID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`stickerimage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`stickerimage` (
  `brandID` TINYINT UNSIGNED NOT NULL,
  `seedsID` SMALLINT NOT NULL,
  `stickerImage` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`brandID`, `seedsID`),
  INDEX `FK__stickerIm__seeds__33F4B129` (`seedsID` ASC) VISIBLE,
  CONSTRAINT `FK__stickerIm__brand__33008CF0`
    FOREIGN KEY (`brandID`)
    REFERENCES `db_organorepublic`.`brand` (`brandID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__stickerIm__seeds__33F4B129`
    FOREIGN KEY (`seedsID`)
    REFERENCES `db_organorepublic`.`seeds` (`seedsID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`stickers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`stickers` (
  `seedsID` SMALLINT NOT NULL,
  `ISBN` INT NOT NULL,
  `rolls` TINYINT UNSIGNED NOT NULL,
  `count` SMALLINT NOT NULL,
  PRIMARY KEY (`seedsID`, `ISBN`),
  INDEX `FK__stickers__ISBN__35DCF99B` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `FK__stickers__ISBN__35DCF99B`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__stickers__seedsI__34E8D562`
    FOREIGN KEY (`seedsID`)
    REFERENCES `db_organorepublic`.`seeds` (`seedsID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`stickersdelivered`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`stickersdelivered` (
  `orderDate` DATE NOT NULL,
  `seedsID` SMALLINT NOT NULL,
  `ISBN` INT NOT NULL,
  `rolls` TINYINT UNSIGNED NOT NULL,
  `count` SMALLINT NOT NULL,
  PRIMARY KEY (`orderDate`, `seedsID`, `ISBN`),
  INDEX `FK__stickersD__seeds__38B96646` (`seedsID` ASC) VISIBLE,
  INDEX `FK__stickersDe__ISBN__39AD8A7F` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `FK__stickersD__seeds__38B96646`
    FOREIGN KEY (`seedsID`)
    REFERENCES `db_organorepublic`.`seeds` (`seedsID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__stickersDe__ISBN__39AD8A7F`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`stickersorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`stickersorder` (
  `orderDate` DATE NOT NULL,
  `seedsID` SMALLINT NOT NULL,
  `ISBN` INT NOT NULL,
  `rolls` TINYINT UNSIGNED NOT NULL,
  `count` SMALLINT NOT NULL,
  `estShipDate` DATE NOT NULL,
  `estDeliveryDate` DATE NOT NULL,
  `price` DECIMAL(19,4) NOT NULL,
  PRIMARY KEY (`orderDate`, `seedsID`, `ISBN`),
  INDEX `FK__stickersOr__ISBN__36D11DD4` (`ISBN` ASC) VISIBLE,
  INDEX `FK__stickersO__seeds__37C5420D` (`seedsID` ASC) VISIBLE,
  CONSTRAINT `FK__stickersO__seeds__37C5420D`
    FOREIGN KEY (`seedsID`)
    REFERENCES `db_organorepublic`.`seeds` (`seedsID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__stickersOr__ISBN__36D11DD4`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`storagetype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`storagetype` (
  `storageTypeID` TINYINT UNSIGNED NOT NULL,
  `storageType` CHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`storageTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`suppliers` (
  `supID` SMALLINT NOT NULL,
  `supName` CHAR(60) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`supID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`sysdiagrams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`sysdiagrams` (
  `name` VARCHAR(160) NOT NULL,
  `principal_id` INT NOT NULL,
  `diagram_id` INT NOT NULL,
  `version` INT NULL DEFAULT NULL,
  `definition` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`diagram_id`),
  UNIQUE INDEX `UK_principal_name` (`principal_id` ASC, `name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`typeofmasterbag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`typeofmasterbag` (
  `typeMBID` TINYINT UNSIGNED NOT NULL,
  `typeMB` CHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `size` DOUBLE NOT NULL,
  `unitOfMeasurment` CHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`typeMBID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`typeofseeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`typeofseeds` (
  `typeSeedsID` TINYINT UNSIGNED NOT NULL,
  `nameSeedsType` CHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`typeSeedsID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`warehouse` (
  `sectionID` SMALLINT NOT NULL,
  `sectionName` CHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `seedsID` SMALLINT NOT NULL,
  `seedsWeight` DOUBLE NOT NULL,
  PRIMARY KEY (`sectionID`, `seedsID`),
  INDEX `FK__warehouse__seeds__3AA1AEB8` (`seedsID` ASC) VISIBLE,
  CONSTRAINT `FK__warehouse__seeds__3AA1AEB8`
    FOREIGN KEY (`seedsID`)
    REFERENCES `db_organorepublic`.`seeds` (`seedsID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`warehousestorage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`warehousestorage` (
  `ISBN` INT NOT NULL,
  `countSets` SMALLINT NOT NULL,
  `lot` CHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `date` DATE NOT NULL,
  `boxTypeID` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ISBN`, `date`),
  INDEX `FK_warehouseStorage_boxType` (`boxTypeID` ASC) VISIBLE,
  CONSTRAINT `FK__warehouseS__ISBN__3B95D2F1`
    FOREIGN KEY (`ISBN`)
    REFERENCES `db_organorepublic`.`sets` (`ISBN`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_warehouseStorage_boxType`
    FOREIGN KEY (`boxTypeID`)
    REFERENCES `db_organorepublic`.`boxtype` (`boxTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`workinghours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`workinghours` (
  `emplID` SMALLINT NOT NULL,
  `date` DATE NOT NULL,
  `session` TINYINT UNSIGNED NOT NULL,
  `hourIN` TIME NOT NULL,
  `hourOut` TIME NOT NULL,
  `breakUse` TINYINT(1) NOT NULL,
  `breakTIme` TIME NOT NULL,
  PRIMARY KEY (`emplID`, `date`, `session`),
  CONSTRAINT `FK__workingHo__emplI__3C89F72A`
    FOREIGN KEY (`emplID`)
    REFERENCES `db_organorepublic`.`employee` (`employeeID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`workstation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`workstation` (
  `seedsID` SMALLINT NOT NULL,
  `containerID` TINYINT UNSIGNED NOT NULL,
  `weight` DOUBLE NOT NULL,
  PRIMARY KEY (`seedsID`),
  CONSTRAINT `FK__workStati__seeds__3D7E1B63`
    FOREIGN KEY (`seedsID`)
    REFERENCES `db_organorepublic`.`seeds` (`seedsID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`ziplockblank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`ziplockblank` (
  `idZipLock` SMALLINT NOT NULL,
  `count` SMALLINT NOT NULL,
  PRIMARY KEY (`idZipLock`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`ziplockemptysticker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`ziplockemptysticker` (
  `seedsID` SMALLINT NOT NULL,
  `date` DATE NOT NULL,
  `emplID` SMALLINT NOT NULL,
  `idZipLockBlank` SMALLINT NOT NULL,
  `count` SMALLINT NOT NULL,
  PRIMARY KEY (`seedsID`, `date`, `emplID`),
  INDEX `FK__ziplockEm__emplI__3F6663D5` (`emplID` ASC) VISIBLE,
  INDEX `FK__ziplockEm__idZip__414EAC47` (`idZipLockBlank` ASC) VISIBLE,
  CONSTRAINT `FK__ziplockEm__emplI__3F6663D5`
    FOREIGN KEY (`emplID`)
    REFERENCES `db_organorepublic`.`employee` (`employeeID`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__ziplockEm__idZip__414EAC47`
    FOREIGN KEY (`idZipLockBlank`)
    REFERENCES `db_organorepublic`.`ziplockblank` (`idZipLock`)
    ON DELETE CASCADE,
  CONSTRAINT `FK__ziplockEm__seeds__3E723F9C`
    FOREIGN KEY (`seedsID`)
    REFERENCES `db_organorepublic`.`seeds` (`seedsID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`ziplocksblankdelivered`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`ziplocksblankdelivered` (
  `orderDate` DATE NOT NULL,
  `idZipLock` SMALLINT NOT NULL,
  `count` SMALLINT NOT NULL,
  PRIMARY KEY (`orderDate`, `idZipLock`),
  INDEX `FK__zipLocksB__idZip__4336F4B9` (`idZipLock` ASC) VISIBLE,
  CONSTRAINT `FK__zipLocksB__idZip__4336F4B9`
    FOREIGN KEY (`idZipLock`)
    REFERENCES `db_organorepublic`.`ziplockblank` (`idZipLock`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_organorepublic`.`ziplocksblankorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organorepublic`.`ziplocksblankorder` (
  `orderDate` DATE NOT NULL,
  `count` SMALLINT NOT NULL,
  `price` DECIMAL(19,4) NOT NULL,
  `idZipLock` SMALLINT NOT NULL,
  `estShipDate` DATE NOT NULL,
  `estDeliveryDate` DATE NOT NULL,
  PRIMARY KEY (`orderDate`, `idZipLock`),
  INDEX `FK__zipLocksB__idZip__4242D080` (`idZipLock` ASC) VISIBLE,
  CONSTRAINT `FK__zipLocksB__idZip__4242D080`
    FOREIGN KEY (`idZipLock`)
    REFERENCES `db_organorepublic`.`ziplockblank` (`idZipLock`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
